name: Action OICD Test
on: workflow_dispatch
permissions:
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: yahavi/setup-jfrog-cli@user-with-oidc
      env:
        JF_USER: yahavi
        JF_URL: ${{ secrets.JF_URL }}
      with:
        oidc-provider-name: yahav
        oidc-audience: yahav-aud

    - run: jf docker pull ecosysjfrog.jfrog.io/docker-remote/netdata/netdata:v1.33.1
