name: Action OICD Test
on: workflow_dispatch
permissions:
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: yahavi/setup-jfrog-cli@improve-oidc
      env:
        JF_URL: ${{ secrets.JF_URL }}
      with:
        oidc-provider-name: yahav

    - run: jf rt s "artifactory-build-info/"
