name: Action OICD Test
on: workflow_dispatch
permissions:
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ secrets.JF_URL }}
      with:
        oidc-provider-name: yahav
        oidc-audience: yahav-aud

    - run: jf docker pull ecosysjfrog.jfrog.io/docker-remote/netdata/netdata:v1.33.1
      env:
        JFROG_CLI_LOG_LEVEL: DEBUG

